defmodule DerpyToolsWeb.Snippets do
  @moduledoc """
  Embeds all the code snippets generated by Chroma.
  """
  use Phoenix.Component

  embed_templates "snippets/**/*"

  attr :snippet, :atom
  attr :style_nonce, :string
  attr :name, :string, default: "Filename"
  attr :caption, :string, default: "Description"

  def render(assigns) do
    ~H"""
    <figure class="code-snippet relative">
      <div class="label purple"><%= @name %></div>
      <%= apply(__MODULE__, @snippet, [assigns]) %>
      <figcaption class="flex justify-center"><%= @caption %></figcaption>
    </figure>
    """
  end
end
